import { opportunityRequest } from '@/server/opportunities/client';
import { validateFinderData } from '@/features/opportunities/types';
import { requireFinderOwner } from '@/server/opportunities/access';
import { defaultSkills, statuses, type Assessment } from '@/features/opportunities/lib/matching';
import { saveProfile, collectNow, updateOpportunity } from '@/features/opportunities/server/actions';
import { SubmitButton } from '@/features/opportunities/components/SubmitButton';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Opportunity finder', robots: { index: false, follow: false } };
const field = 'w-full rounded-lg bg-input/30 px-3 py-2 text-sm ring-1 ring-foreground/10 focus-visible:outline-none focus-visible:ring-ring';
const notices: Record<string, string> = { success: 'Collection completed. Review your results and collection history below.', failed: 'Source unavailable. Your saved opportunities are safe; try again tomorrow.', cooldown: 'Already checked within the last 20 hours. Check your saved opportunities below.', disabled: 'Enable collection in your search profile first.' };
export default async function Page({ searchParams }: { searchParams: Promise<{ status?: string; run?: string }> }) {
  await requireFinderOwner();
  const query = await searchParams;
  const filter = (statuses as readonly string[]).includes(query.status || '') ? query.status : undefined;
  const { profile, jobs, runs } = validateFinderData(await opportunityRequest<unknown>({ operation: 'list', status: filter }));
  return <main className="rcentz-dashboard-frame px-4 py-6 sm:px-6 lg:px-8"><div className="rcentz-dashboard-inner mx-auto w-full max-w-[1200px] space-y-5">
    <header className="space-y-3"><p className="text-sm text-muted-foreground">Private workspace · Jobs & contracts</p><h1 className="text-3xl font-semibold">Opportunities worth your time.</h1><p className="max-w-2xl text-muted-foreground">Automatic discovery with clear reasons, honest gaps and your decision at the centre. Business prospects and proposal drafting will follow.</p></header>
    {query.run && notices[query.run] ? <p role="status" className="rounded-xl border bg-muted p-4">{notices[query.run]}</p> : null}
    <Card className="p-5"><h2 className="mb-4 text-lg font-semibold">Your search profile</h2><form action={saveProfile} className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 sm:col-span-2"><span className="text-sm">Skills, separated by commas</span><Input name="skills" defaultValue={(profile?.skills || defaultSkills).join(', ')} required maxLength={1000} /></label><label className="space-y-2"><span className="text-sm">Years of experience (minimum you can claim)</span><Input name="experienceYears" type="number" min="0" max="50" defaultValue={profile?.experienceYears ?? 2} required /></label><div className="flex items-center"><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="enabled" defaultChecked={profile?.enabled ?? false} />Enable daily collection</label></div><div><SubmitButton>Save profile</SubmitButton></div></form><p className="mt-4 text-xs text-muted-foreground">You are based in Nigeria. Worldwide wording is a clue, not verified eligibility. Profile changes affect the next collection.</p></Card>
    <Card className="flex flex-wrap flex-row items-center justify-between gap-4 p-5"><div><h2 className="font-semibold">Remotive · Public job feed</h2><p className="mt-1 text-sm text-muted-foreground">Checks once daily around 8 a.m. Lagos after deployment and configuration. Feed listings are delayed by 24 hours.</p><p className="mt-1 text-xs text-muted-foreground">Results and collection history appear here; email delivery is not enabled in this release.</p></div><form action={collectNow}><SubmitButton>Check jobs</SubmitButton></form></Card>
    <form className="flex flex-wrap items-end gap-3"><label className="space-y-2"><span className="text-sm">Application status</span><select name="status" defaultValue={filter || ''} className={field}><option value="">All statuses</option>{statuses.map(s => <option key={s} value={s}>{s.toLowerCase().replaceAll('_', ' ')}</option>)}</select></label><Button type="submit" variant="outline">Filter</Button></form>
    <div className="grid gap-5 lg:grid-cols-2">{jobs.map(job => { const a = job.assessment as Assessment; return <Card key={job.id} className="flex flex-col gap-4 p-5"><div><p className="text-xs font-medium text-muted-foreground">{job.company} · {job.jobType.replaceAll('_', ' ')}</p><h2 className="mt-2 text-xl font-semibold">{job.title}</h2><p className="mt-2 text-sm">{a.verdict} · Stack fit {job.score}/100</p></div><p className="text-sm text-muted-foreground">{job.location || 'Location not specified'} · {job.salary || 'Salary not supplied'}</p><p className="text-sm">{a.eligibility}</p><div className="space-y-2 text-sm"><p><strong>Matches:</strong> {a.matched.join(', ') || 'No skill keywords found'}</p>{a.concerns.map(c => <p key={c} className="text-foreground">{c}</p>)}{a.questions.map(q => <p key={q} className="text-muted-foreground">{q}</p>)}</div><p className="text-xs text-muted-foreground">Published {new Date(job.publishedAt).toLocaleDateString('en-GB', { timeZone: 'Africa/Lagos' })} · Last seen {new Date(job.lastSeenAt).toLocaleDateString('en-GB', { timeZone: 'Africa/Lagos' })} · {job.sourceState === 'LISTED' ? 'Listed in source feed; employer opening not independently verified.' : 'Missing from latest feed; closure unconfirmed.'}</p><details className="text-sm"><summary className="cursor-pointer font-medium">Read source description</summary><p className="mt-3 whitespace-pre-wrap leading-relaxed text-muted-foreground">{job.description}</p></details><a className="font-medium text-primary underline" href={job.url} target="_blank" rel="noopener noreferrer">View listing on Remotive ↗</a><form action={updateOpportunity} className="mt-auto space-y-3 border-t pt-4"><input type="hidden" name="id" value={job.id} /><label className="block space-y-1"><span className="text-xs">Your decision</span><select name="status" defaultValue={job.status} className={field}>{statuses.map(s => <option key={s} value={s}>{s.toLowerCase()}</option>)}</select></label><label className="block space-y-1"><span className="text-xs">Notes / why this does or does not fit</span><Textarea name="notes" defaultValue={job.notes} maxLength={2000} rows={2} /></label><SubmitButton>Save decision</SubmitButton></form></Card>; })}</div>
    {!jobs.length ? <p className="rounded-2xl border border-dashed p-8 text-center text-muted-foreground">{profile ? 'No opportunities for this view yet. Enable collection and check the source.' : 'Save your profile to begin. No sample jobs are inserted.'}</p> : null}
    <Card className="p-5"><h2 className="mb-3 font-semibold">Collection history</h2>{runs.length ? runs.map(run => <p key={run.id} className="mb-2 text-sm text-muted-foreground">{new Date(run.startedAt).toLocaleString('en-GB', { timeZone: 'Africa/Lagos' })} · {run.status} · {run.fetched} fetched · {run.added} new{run.message ? ' · ' + run.message : ''}</p>) : <p className="text-sm text-muted-foreground">No runs yet.</p>}</Card>
    <p className="text-xs text-muted-foreground">Keyword-based assessment, not a hiring prediction. Up to 100 results, strongest stack matches first. Nothing is submitted or sent to employers automatically.</p>
  </div></main>;
}
